# This is a basic workflow to help you get started with Actions

name: Accessibility

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "axe"
  axe:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Runs a single command using the runners shell
      - name: Install & run serve
        run: npm install serve -g && serve & npx wait-on http://localhost:3000

      - name: Run Accessibility Tool
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3000 --browser chrome --verbose --show-errors
